In [1]:
from datetime import date, timedelta,datetime

import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
import lightgbm as lgb

In [2]:
pred = pd.read_csv("aaaa.csv")
sub = pd.read_csv("holiday_substrace.csv")

In [3]:
del(sub["Unnamed: 0"])
sub["diffrence"] = sub["unit_sales"]
del(sub["unit_sales"])

In [4]:
del(pred["Unnamed: 0"])
pred["date"] = pred["level_2"]
del(pred["level_2"])

In [5]:
df_test = pd.read_csv(
    "test.csv", usecols=[0, 1, 2, 3],
      # , date_parser=parser
)

In [7]:
df_test.dtypes

id            int64
date         object
store_nbr     int64
item_nbr      int64
dtype: object

In [12]:
pred["diffrence"] = pred["diffrence"].apply(lambda x : -x)

In [13]:
pred = pd.merge(pred,sub,how="outer",on=["store_nbr","item_nbr"])
pred["unit_sales"] = pred["unit_sales"].apply(lambda x:x if 0<x else 0)

         store_nbr  item_nbr  unit_sales        date  diffrence
0                1     96995    0.192587  2017-08-16   0.114284
1                1     96995    0.184109  2017-08-17   0.114284
2                1     96995    0.205657  2017-08-18   0.114284
3                1     96995    0.252932  2017-08-19   0.114284
4                1     96995    0.250391  2017-08-20   0.114284
5                1     96995    0.223656  2017-08-21   0.114284
6                1     96995    0.192692  2017-08-22   0.114284
7                1     96995    0.199382  2017-08-23   0.114284
8                1     96995    0.179892  2017-08-24   0.114284
9                1     96995    0.243392  2017-08-25   0.114284
10               1     96995    0.289689  2017-08-26   0.114284
11               1     96995    0.272099  2017-08-27   0.114284
12               1     96995    0.221858  2017-08-28   0.114284
13               1     96995    0.207474  2017-08-29   0.114284
14               1     96995    0.196496  2017-08-30   0.114284
15               1     96995    0.182842  2017-08-31   0.114284
16               1     99197    0.321544  2017-08-16   0.203530
17               1     99197    0.304224  2017-08-17   0.203530
18               1     99197    0.386358  2017-08-18   0.203530
19               1     99197    0.379962  2017-08-19   0.203530
20               1     99197    0.245726  2017-08-20   0.203530
21               1     99197    0.292401  2017-08-21   0.203530
22               1     99197    0.292284  2017-08-22   0.203530
23               1     99197    0.335733  2017-08-23   0.203530
24               1     99197    0.284671  2017-08-24   0.203530
25               1     99197    0.372961  2017-08-25   0.203530
26               1     99197    0.395379  2017-08-26   0.203530
27               1     99197    0.256383  2017-08-27   0.203530
28               1     99197    0.320624  2017-08-28   0.203530
29               1     99197    0.317856  2017-08-29   0.203530
...            ...       ...         ...         ...        ...
2680210         54   2113914    2.161040  2017-08-18  -0.144294
2680211         54   2113914    2.370311  2017-08-19  -0.144294
2680212         54   2113914    2.830076  2017-08-20  -0.144294
2680213         54   2113914    2.333085  2017-08-21  -0.144294
2680214         54   2113914    2.529021  2017-08-22  -0.144294
2680215         54   2113914    2.315226  2017-08-23  -0.144294
2680216         54   2113914    1.748140  2017-08-24  -0.144294
2680217         54   2113914    1.206993  2017-08-25  -0.144294
2680218         54   2113914    1.984948  2017-08-26  -0.144294
2680219         54   2113914    2.038384  2017-08-27  -0.144294
2680220         54   2113914    1.267858  2017-08-28  -0.144294
2680221         54   2113914    1.373787  2017-08-29  -0.144294
2680222         54   2113914    1.214223  2017-08-30  -0.144294
2680223         54   2113914    1.238873  2017-08-31  -0.144294
2680224         54   2116416    0.470786  2017-08-16   0.167391
2680225         54   2116416    0.425780  2017-08-17   0.167391
2680226         54   2116416    0.357757  2017-08-18   0.167391
2680227         54   2116416    0.465812  2017-08-19   0.167391
2680228         54   2116416    0.658026  2017-08-20   0.167391
2680229         54   2116416    0.416711  2017-08-21   0.167391
2680230         54   2116416    0.413465  2017-08-22   0.167391
2680231         54   2116416    0.338150  2017-08-23   0.167391
2680232         54   2116416    0.416215  2017-08-24   0.167391
2680233         54   2116416    0.371630  2017-08-25   0.167391
2680234         54   2116416    0.377154  2017-08-26   0.167391
2680235         54   2116416    0.567904  2017-08-27   0.167391
2680236         54   2116416    0.452532  2017-08-28   0.167391
2680237         54   2116416    0.468744  2017-08-29   0.167391
2680238         54   2116416    0.423932  2017-08-30   0.167391
2680239         54   2116416    0.358326  2017-08-31   0.167391

[2680240 rows x 5 columns]

In [14]:
pred[pred["date"] == "2017-08-24"]["unit_sales"] += pred[pred["date"] == "2017-08-24"]["diffrence"]

C:\Users\br141\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [47]:
pred.set_index(["store_nbr","item_nbr","date"],inplace=True)

In [49]:
submission = df_test[["id"]].join(pred, how="left").fillna(0)

In [50]:
submission["unit_sales"] = np.clip(np.expm1(submission["unit_sales"]), 0, 1000)
submission.to_csv('lgb6.csv', float_format='%.4f', index=None)

In [54]:
df_test.reset_index(inplace=True)
pred.reset_index(inplace=True)

In [80]:
submission = pd.merge(pred,df_test,how="outer",on=["store_nbr","item_nbr","date"])

In [74]:
submission.drop(["store_nbr","item_nbr","date"],axis=1,inplace=True)

In [9]:
submission = pd.merge(pred,df_test,how="left",on=["store_nbr","item_nbr","date"])

In [11]:
submission.drop(["store_nbr","date","item_nbr"])

ValueError: labels ['store_nbr' 'date' 'item_nbr'] not contained in axis

In [13]:
del(submission["store_nbr"])
del(submission["date"])
del(submission["item_nbr"])

In [16]:
submission["unit_sales"] = np.clip(np.expm1(submission["unit_sales"]), 0, 1000)
submission.to_csv('lgb7.csv', float_format='%.4f', index=None)